AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Texas Insights Engine - AI-Powered Business Intelligence Interview System

Globals:
  Function:
    Timeout: 120
    Runtime: python3.9
    MemorySize: 512
    Environment:
      Variables:
        INTERVIEWS_TABLE: !Ref InterviewsTable
        USERS_TABLE: !Ref UsersTable
        AUDIT_TABLE: !Ref AuditLogTable
        INSIGHTS_TABLE: !Ref InsightsEngineTable
        CONSENT_TABLE: !Ref ConsentTable
        S3_BUCKET: !Ref DataBucket
        BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0
        KENDRA_INDEX_ID: !If [CreateKendra, !GetAtt KendraIndex.Id, ""]
    Layers:
      - !Ref SharedLayer

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  EnableKendra:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: Enable Kendra index (costs ~$810/month for Developer Edition)
  FrontendUrl:
    Type: String
    Default: "http://localhost:3000"
    Description: Frontend URL for CORS

Conditions:
  CreateKendra: !Equals [!Ref EnableKendra, "true"]

Resources:
  # ============================================================
  # COGNITO - Authentication
  # ============================================================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub texas-insights-${Stage}-pool
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: true
          Mutable: true
        - Name: custom:role
          AttributeDataType: String
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub texas-insights-${Stage}-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  # ============================================================
  # S3 - Document Storage
  # ============================================================
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub tamu-insights-${Stage}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, PUT, POST]
            AllowedOrigins:
              - !Ref FrontendUrl
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: AuditRetention
            Prefix: audit/
            Status: Enabled
            ExpirationInDays: 730
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ============================================================
  # DYNAMODB - Metadata Storage
  # ============================================================
  InterviewsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub texas-insights-interviews-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub texas-insights-users-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  AuditLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub texas-insights-audit-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true

  InsightsEngineTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub texas-insights-engine-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  ConsentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub texas-insights-consent-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  # ============================================================
  # LAMBDA LAYER - Shared Code
  # ============================================================
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub texas-insights-shared-${Stage}
      ContentUri: layers/shared/
      CompatibleRuntimes: [python3.9]
    Metadata:
      BuildMethod: makefile

  # ============================================================
  # API GATEWAY
  # ============================================================
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub texas-insights-api-${Stage}
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key'"
        AllowOrigin: !Sub "'${FrontendUrl}'"
      Auth:
        DefaultAuthorizer: CognitoAuth
        Authorizers:
          CognitoAuth:
            UserPoolArn: !GetAtt UserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: false
      # CORS on error responses (e.g. 401 from authorizer) so browser can read the response
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: !Sub "'${FrontendUrl}'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: !Sub "'${FrontendUrl}'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key'"

  # ============================================================
  # LAMBDA FUNCTIONS
  # ============================================================
  CreateSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub texas-insights-create-session-${Stage}
      CodeUri: functions/create_session/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InterviewsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditLogTable
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action: states:StartExecution
              Resource: !Ref BriefGenerationStateMachine
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref BriefGenerationStateMachine
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /sessions
            Method: POST

  GetSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub texas-insights-get-session-${Stage}
      CodeUri: functions/get_session/
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref InterviewsTable
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /sessions/{sessionId}
            Method: GET

  ListSessionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub texas-insights-list-sessions-${Stage}
      CodeUri: functions/list_sessions/
      Handler: app.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref InterviewsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /sessions
            Method: GET

  IngestSourcesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub texas-insights-ingest-${Stage}
      CodeUri: functions/ingest_sources/
      Handler: app.handler
      Timeout: 300
      MemorySize: 1024
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InterviewsTable
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditLogTable
        - Statement:
            - Effect: Allow
              Action:
                - textract:DetectDocumentText
                - textract:AnalyzeDocument
                - comprehend:DetectEntities
                - comprehend:DetectKeyPhrases
                - comprehend:DetectPiiEntities
              Resource: "*"

  GenerateBriefFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub texas-insights-generate-brief-${Stage}
      CodeUri: functions/generate_brief/
      Handler: app.handler
      Timeout: 300
      MemorySize: 1024
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InterviewsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditLogTable
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "arn:aws:bedrock:*::foundation-model/*"

  QualityCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub texas-insights-quality-check-${Stage}
      CodeUri: functions/quality_check/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InterviewsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditLogTable
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: "arn:aws:bedrock:*::foundation-model/*"

  SendPacketFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub texas-insights-send-packet-${Stage}
      CodeUri: functions/send_packet/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InterviewsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditLogTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConsentTable
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action: ses:SendEmail
              Resource: "*"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /sessions/{sessionId}/send-packet
            Method: POST

  SubmitCorrectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub texas-insights-corrections-${Stage}
      CodeUri: functions/submit_corrections/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InterviewsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditLogTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /sessions/{sessionId}/corrections
            Method: POST
            Auth:
              Authorizer: NONE

  UpdateBriefFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub texas-insights-update-brief-${Stage}
      CodeUri: functions/update_brief/
      Handler: app.handler
      Timeout: 300
      MemorySize: 1024
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InterviewsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditLogTable
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "arn:aws:bedrock:*::foundation-model/*"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /sessions/{sessionId}/update-brief
            Method: POST

  PostCallSynthesisFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub texas-insights-synthesis-${Stage}
      CodeUri: functions/post_call_synthesis/
      Handler: app.handler
      Timeout: 300
      MemorySize: 1024
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InterviewsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuditLogTable
        - DynamoDBCrudPolicy:
            TableName: !Ref InsightsEngineTable
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: "arn:aws:bedrock:*::foundation-model/*"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /sessions/{sessionId}/synthesis
            Method: POST

  # ============================================================
  # STEP FUNCTIONS - Brief Generation Pipeline
  # ============================================================
  BriefGenerationStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub texas-insights-brief-pipeline-${Stage}
      DefinitionUri: statemachine/brief_generation.asl.json
      DefinitionSubstitutions:
        IngestSourcesFunctionArn: !GetAtt IngestSourcesFunction.Arn
        GenerateBriefFunctionArn: !GetAtt GenerateBriefFunction.Arn
        QualityCheckFunctionArn: !GetAtt QualityCheckFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref IngestSourcesFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateBriefFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref QualityCheckFunction

  # ============================================================
  # KENDRA (Optional - enabled via parameter)
  # ============================================================
  KendraIndex:
    Type: AWS::Kendra::Index
    Condition: CreateKendra
    Properties:
      Name: !Sub texas-insights-kendra-${Stage}
      Edition: DEVELOPER_EDITION
      RoleArn: !GetAtt KendraRole.Arn

  KendraRole:
    Type: AWS::IAM::Role
    Condition: CreateKendra
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: kendra.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  KendraS3DataSource:
    Type: AWS::Kendra::DataSource
    Condition: CreateKendra
    Properties:
      IndexId: !GetAtt KendraIndex.Id
      Name: !Sub texas-insights-s3-source-${Stage}
      Type: S3
      DataSourceConfiguration:
        S3Configuration:
          BucketName: !Ref DataBucket
          InclusionPrefixes:
            - uploads/
            - extracted/
      RoleArn: !GetAtt KendraS3Role.Arn

  KendraS3Role:
    Type: AWS::IAM::Role
    Condition: CreateKendra
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: kendra.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: KendraS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub "${DataBucket.Arn}/*"

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
  S3Bucket:
    Description: S3 Bucket Name
    Value: !Ref DataBucket
  InterviewsTableName:
    Description: DynamoDB Interviews Table
    Value: !Ref InterviewsTable
  StateMachineArn:
    Description: Brief Generation State Machine ARN
    Value: !Ref BriefGenerationStateMachine
  KendraIndexId:
    Condition: CreateKendra
    Description: Kendra Index ID
    Value: !GetAtt KendraIndex.Id
